[tool.poetry]
name = "webapp"
version = "0.1.0"
description = ""
authors = ["lildng <lilydaganaudfavre@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
